name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phase0:
    name: phase0
    uses: justK5/edulite-ops/.github/workflows/ci-reusable.yml@main
    secrets: inherit
